### ISSUE TITLE
Failed to execute "remote-exec" portions of the main.tf

### ISSUE THREAD

**Issue by dglinder** [TribalNightOwl/okd4-esxi-infra#1]
**Describe the bug**
Adding a remote exec provisioner causes SSH connection errors.

**To Reproduce**

1. Starting with the example in the README.md (https://github.com/josenk/terraform-provider-esxi/blob/master/README.md#how-to-use-and-configure-a-maintf-file)

2. Add this code between the ```provider "esxi"``` and ```resource "esxi_guest" "vmtest"```:

```
resource "null_resource" "esxi_network" {
  provisioner "remote-exec" {
    inline = [
      "whoami > /tmp/test.out"
    ]
  }
}
```

3. Run `terraform init && terraform destroy --auto-approve && terraform apply -auto-approve`

4. The `terraform apply` output repeats this until it times out:

```
null_resource.esxi_network (remote-exec): Connecting to remote host via SSH...
null_resource.esxi_network (remote-exec):   Host:
null_resource.esxi_network (remote-exec):   User: root
null_resource.esxi_network (remote-exec):   Password: false
null_resource.esxi_network (remote-exec):   Private key: false
null_resource.esxi_network (remote-exec):   Certificate: false
null_resource.esxi_network (remote-exec):   SSH Agent: false
null_resource.esxi_network (remote-exec):   Checking Host Key: false
```

*NOTE:* Even with the ```inline = [ ... ]``` block commented out, the error still occurs.

**Expected behavior**
The command is executed on the ESXi system and the ```/tmp/test.out``` is created.

**Terraform files**
Here is the Terraform file I'm using:
```
terraform {
  required_version = ">= 0.12"
}

provider "esxi" {
  esxi_hostname      = "esx.local"
  esxi_hostport      = "22"
  esxi_hostssl       = "443"
  esxi_username      = "root"
  esxi_password      = "REDACTED"
}

resource "null_resource" "esxi_network" {
  provisioner "remote-exec" {
  }
}

resource "esxi_guest" "vmtest" {
  guest_name         = "vmtest"
  disk_store         = "datastore1"

  network_interfaces {
    virtual_network = "VM Network"
  }
}
```

**Desktop (please complete the following information):**
 - OS: CentOS 7.8
 - Terraform Version: output from `terraform version`:
```
Terraform v0.12.29
+ provider.esxi v1.7.0
+ provider.null v2.1.2
```
 - Ovftool Version: VMware ovftool 4.4.0 (build-16360108)
 - This Plugin Version: v1.7.0

**Comment by dglinder** [comment]
**Additional context**
Running this `main.cf`:
```
terraform {
  required_version = ">= 0.12"
}

provider "esxi" {
  esxi_hostname      = "esx.lab.linder.org"
  esxi_hostport      = "22"
  esxi_hostssl       = "443"
  esxi_username      = "root"
  esxi_password      = "q7-19ezx"
}

resource "null_resource" "esxi_network" {
  provisioner "remote-exec" {
    inline = [
      "whoami > /tmp/test.out",
    ]
  }
}

resource "esxi_guest" "vmtest" {
  guest_name         = "vmtest"
  disk_store         = "datastore1"
  network_interfaces {
    virtual_network = "VM Network"
  }
}
```

And executing these commands with TRACE level logging:
```
export TF_LOG=TRACE
export TF_LOG_PATH=/tmp/tf.log
terraform init
terraform destroy -auto-approve
rm -f /tmp/tf.log
terraform apply -auto-approve
```

I let it repeat the SSH connection until 10 seconds have elapsed, then press Ctrl-C until it exits.

The `tf.log` file is attached.
[tf.log](https://github.com/josenk/terraform-provider-esxi/files/5048127/tf.log)

**Comment by dglinder** [comment]
@TribalNightOwl , I assume your example worked for you.  Can you reply with the versions of your Os, Terraform, OVFtool, and the version of the terraform-provider-esxi plugin?

**Comment by TribalNightOwl** [comment]
I don't use OVFtool, all the connections to the ESXi server are via SSH (per this terreform provider requirements).

From your log file I suspect that your ESXi server doesn't have SSH access enabled.
```
remote-exec-provisioner (internal) 2020/08/09 17:26:12 [DEBUG] Connecting to :22 for SSH
remote-exec-provisioner (internal) 2020/08/09 17:26:12 [DEBUG] Connection established. Handshaking for user root
remote-exec-provisioner (internal) 2020/08/09 17:26:12 [WARN] SSH authentication failed (root@:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
remote-exec-provisioner (internal) 2020/08/09 17:26:12 [WARN] retryable error: SSH authentication failed (root@:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

Before running this, make sure to enable ssh access, and that you can login passwordless to your ESXi server.

**Comment by dglinder** [comment]
The SSH access to the ESXi server does work - if I remove the "provisioner / remote-exec / inline" sections the VMs are produced.

I branched your code (https://github.com/dglinder/okd4-esxi-infra/blob/master/terraform/main.tf) and comment out the "depends_on" calls the builds work (assuming I manually call the "esxcli network" commands).  (I'm also adding the calls to use a template and install the packages using the Ansible playbooks provided in your repo.)

I noticed the warning specifically says this:

> retryable error: SSH authentication failed (**root@:22**): ssh: handshake failed

Note the "root@:22" - the hostname is missing.  I'm not a Go programmer, but I think it's somewhere in this section of the `esxi_remote_cmds.go` code:
    https://github.com/josenk/terraform-provider-esxi/blob/86264ae1473e088c6a3275d9ad21859a72e7e44e/esxi/esxi_remote_cmds.go#L35

I'm not familiar enough with Go to know where to look next.

**Comment by TribalNightOwl** [comment]
I just ran this:
```
terraform {
  required_version = ">= 0.12"
  required_providers {
    esxi = {
      version = "~> 1.7"
    }
  }
}

resource "null_resource" "esxi_network" {
  # These triggers are just a workaround to be able to use variables in the destroy provisioner
  triggers = {
    always_run = "${timestamp()}"
    netname = var.okd_network
    switch  = var.vswitch
    host    = var.esxi_host
  }

  connection {
    host = self.triggers.host
  }

  provisioner "remote-exec" {
    inline = [
      "esxcli network vswitch standard portgroup add --portgroup-name=${var.okd_network} --vswitch-name=${var.vswitch}",
      "esxcli network vswitch standard portgroup set -p ${var.okd_network} --vlan-id ${var.vlan_id}",
    ]
  }

  provisioner "remote-exec" {
    when    = destroy
    inline = [
      "esxcli network vswitch standard portgroup remove --portgroup-name=${self.triggers.netname} --vswitch-name=${self.triggers.switch}",
    ]
  }
}

provider "esxi" {
  esxi_hostname      = var.esxi_host
  esxi_hostport      = "22"
  esxi_hostssl       = "443"
  esxi_username      = var.esxi_username
  esxi_password      = var.esxi_password
}

resource "esxi_guest" "GH-okd4-bootstrap" {
  guest_name     = "GH-okd4-bootstrap"
  numvcpus       = "4"
  memsize        = "16384"  # in Mb
  boot_disk_size = "120" # in Gb
  boot_disk_type = "thin"
  disk_store     = var.datastore
  guestos        = "fedora-64"
  power          = "off"
  virthwver      = "13"

  network_interfaces {
    mac_address     = "00:50:56:02:01:01"
    virtual_network = var.okd_network
  }
  depends_on = [null_resource.esxi_network]
}
```
and it worked fine, it created the network and then it created the VM.

![Screenshot from 2020-08-13 17-02-23](https://user-images.githubusercontent.com/34578120/90186829-d5c47680-dd86-11ea-912f-24e29e1cd400.png)


![Screenshot from 2020-08-13 17-03-10](https://user-images.githubusercontent.com/34578120/90186879-e674ec80-dd86-11ea-8893-a23d260524e8.png)

**Comment by dglinder** [comment]
Thanks, @TribalNightOwl - I'm going to apologize, this was all on me not knowing enough about the "remote-exec" code.

In short, I needed to add the connection information inside the `resource "null_resource" "esxi_network"` section because the `provisioner "remote-exec"` calls were failing.  Once I added those, the remote commands on my ESXi system worked just fine.

A case of PEBCAK ("Problem exists between chair and keyboard") if I ever saw one. :-)

Here's my test playbook that works if others come across this error:
```
terraform {
  required_version = ">= 0.13"
  required_providers {
    esxi = {
      source  = "registry.terraform.io/josenk/esxi" #"josenk/esxi"
      version = "~> 1.7.1"
    }
    null = {
      source = "hashicorp/null"
    }
  }
}

resource "null_resource" "esxi_network" {
  connection {
    type  = "ssh"
    user  = "AUser"
    password = "APassword"
    host  = "esx.homelab.example.com"
  }

  provisioner "remote-exec" {
    inline = [
      "echo BUILDING $(date) | tee -a /tmp/output.txt"
    ]
  }

  provisioner "remote-exec" {
    when = destroy
    inline = [
      "echo DESTROYING $(date) | tee -a /tmp/output.txt"
    ]
  }
}

provider "esxi" {
  esxi_hostname = "esx.homelab.example.com"
  esxi_hostport = "22"
  esxi_hostssl  = "443"
  esxi_username = "AUser"
  esxi_password = "APassword"
}

resource "esxi_guest" "ATestVM" {
  guest_name     = "atestvm"
  disk_store     = "datastore1"
  power          = "off"

  depends_on = [null_resource.esxi_network]
}
```

Adjust the user, password, and ESXi hostnames as needed.
